# Generated by Django 3.0.14 on 2021-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnigmaAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'frauddetectionsystem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('crime', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'investigation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mlmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('crime', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mlmodel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('crime', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='USSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('crime', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ussd',
                'managed': True,
            },
        ),
    ]
